services:
  auth:
    image: quay.io/keycloak/keycloak:26.1
    container_name: auth
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: auth
      KC_HOSTNAME: localhost
      KC_HOSTNAME_URL: https://localhost/auth
      # 古い設定を削除し、新しい設定方法を使用
      KC_PROXY_HEADERS: xforwarded
    command:
      - start-dev
    volumes:
      - auth_data:/opt/keycloak/data

  backend_app:
    build: ./backend_app
    container_name: backend_app
    volumes:
      - ./backend_app:/backend_app
      - backend_node_modules:/backend_app/node_modules

  app:
    build: ./app
    container_name: app
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules

  api:
    build: ./api
    container_name: api
    volumes:
      - ./api/app.py:/app/app.py:ro
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - AUTH_SERVER_URL=http://auth:8080/auth/
      - AUTH_REALM_NAME=oidc-test
      - AUTH_CLIENT_ID=test-client
      - AUTH_CLIENT_SECRET_KEY=wPqKPUjviWs41KvVRpjLYjwSuSg0RQA4

  proxy:
    image: nginx:1.27.4
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/ssl:/etc/nginx/ssl

volumes:
  auth_data:
  backend_node_modules:
  app_node_modules: