services:
  auth:
    image: quay.io/keycloak/keycloak:26.1
    container_name: auth
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - auth_data:/opt/keycloak/data

volumes:
  auth_data: